### ISSUE TITLE
Not deleting versions in a Large Library - Possible Authentication time out?

### ISSUE THREAD

**Issue by TheRealStriff** [Barbarur/NovaPoint#20]
Thanks for this tool, ran it on an old site with two libraries.
set to delete all but 90 versions
The library I targeted as reported by NovaPoint 756576 items. (9 years old)

Runing the tool, it would prompt for re-authentication, as our access tokens last for 7 hours.
At times it would ask for re-authentication more than this, but it seem to carry on.

I'm not sure during this time (Authentication expires, and waiting for me to sign back in),  it resumes where it stopped.

Only because when it finished, it collected just over 520000 items, short of the 756576 reported.
And from the logs no versions deleted.

I check a random file, and had over 190 versions.
Checked the log and the whole directory is not listed as being scanned.

Tried another file and same, over 90 versions, but checking the log, not scanned.

(Going to run a script I have, and modified, can target file types, but seems to get throttled when it starts deleting the versions, plus gets when access token expires it dies., but good test to see if it picks up the missing files (targeting excel files)

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

Do you get any error while running the solution? Did you check the logs from the txt file?

The access token las 60-90 min and it manage squiring a new token by itself. Not sure if you have any configuration on your environment for the the access token to last 90min.

Number of items is base on the information from the library, which includes folders (if I remember well). But deletions of versions only apply to files and folders are ignored.

You can try running the solution for a subfolder to check if versions are deleted. Based on your description, I'm not sure if the solution is not able to catch the files, not able to delete the versions or a different issue.

**Comment by TheRealStriff** [comment]
There were a lot of errors, for individual files, 
below are some examples 

I also tired on smaller libraries and works great.
It seems to just not down some folder structures.
Will configure it to target this and report back.

_2024/06/07 03:33:14 - [AppInfo] - Got access token from memory
2024/06/07 03:33:14 - [AppInfo] - Access Token expiration time: 7/06/2024 4:30:39 AM +00:00
2024/06/07 03:33:14 - [NPLogger] - Error processing Item '/sites/Lake/Shared Documents/Technical/Drill and Blast/Archive/Design/02_North Pit/NO21_VM/NO21_VM_B01-02_Upthrust/Media/GP014797.MP4'
2024/06/07 03:33:14 - [NPLogger] - Exception: Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.
2024/06/07 03:33:14 - [NPLogger] - Trace:    at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAutoRecord.AddFileDetails(ListItem oItem, String versionsDeletedCount, String versionsDeletedMB)_


2024/06/07 03:47:16 - [NPLogger] - Error processing Item '/sites/Lake/Shared Documents/Safety/Work Controls/Audits, Review and Inspections/2023/LV Water Trucks Quantitative Watering Application Review/Quantitative data.xlsx'
2024/06/07 03:47:16 - [NPLogger] - Exception: Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.
2024/06/07 03:47:16 - [NPLogger] - Trace:    at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAutoRecord.AddFileDetails(ListItem oItem, String versionsDeletedCount, String versionsDeletedMB)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RemoveFileVersions(SPOTenantItemRecord resultItem)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RunScriptAsync()
   
   
   
   2024/06/09 21:32:25 - [NPLogger] - Error processing Item '/sites/Lake/Shared Documents/Technical/Mine Planning/Design/01. WEEKLY PLAN/Archive/2021/2021_Archive/Week 12/Lake Vermont Weekly Mine Plan 210317.pptx'
2024/06/09 21:32:25 - [NPLogger] - Exception: Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.
2024/06/09 21:32:25 - [NPLogger] - Trace:    at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAutoRecord.AddFileDetails(ListItem oItem, String versionsDeletedCount, String versionsDeletedMB)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RemoveFileVersions(SPOTenantItemRecord resultItem)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RunScriptAsync()
   
   
   2024/06/09 21:32:56 - [NPLogger] - Error processing Item '/sites/Lake/Shared Documents/People/Training/Administration/Training Specialists Folder/AB Crew/Carly D&I/Carly D&I Wall Posters.pptx'
2024/06/09 21:32:56 - [NPLogger] - Exception: Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.
2024/06/09 21:32:56 - [NPLogger] - Trace:    at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAutoRecord.AddFileDetails(ListItem oItem, String versionsDeletedCount, String versionsDeletedMB)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RemoveFileVersions(SPOTenantItemRecord resultItem)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RunScriptAsync()

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

The error seems the same as the one you reported previously. The issue doesn't occurs while deleting the version, but when adding the information to the CSV file. This is due some properties from the old files not comming through correctly from the server. Still you should be able to see file */sites/Lake/Shared Documents/Technical/Drill and Blast/Archive/Design/02_North Pit/NO21_VM/NO21_VM_B01-02_Upthrust/Media/GP014797.MP4* and the other you posted in the CSV report with the notification of the error. Do you?

For the file versions that are not deleted, do you see those in the .txt logs?

**Comment by TheRealStriff** [comment]
Sorry for late reply, been off due unexpected circumstance.

Yes, you are right can see those files in the CSV file, with the notification of the error.
Will get back to you about the file version not deleted, just doing an audit for versions over the set amount I was aiming for

**Comment by TheRealStriff** [comment]
Ok, so tested the site in question, All good no version over the limit I set (although not in the logs)

Tested another site.
running a script to find versions and their size
File URL	                                                                                                Versions	      File Size (KB)   Version Size (KB)      Total File Size (KB)
/sites/San/SharedDocs/Inventory/SOH/09. September 2018.xlsx	500	              8551.18	     2831532.85	      2840084.03

Targeted the directory using NovaPoint
Error 
Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.

2024/06/16 21:22:50 - [RemoveFileVersionAuto] - Start processing File '09. September 2018.xlsx'
2024/06/16 21:22:50 - [AppInfo] - Getting Access Token for root site https://o365XXX.sharepoint.com
2024/06/16 21:22:50 - [AppInfo] - Got access token from memory
2024/06/16 21:22:50 - [AppInfo] - Access Token expiration time: 16/06/2024 10:27:00 PM +00:00
2024/06/16 21:22:52 - [NPLogger] - Error processing Item '/sites/San/SharedDocs/Inventory/SOH/09. September 2018.xlsx'
2024/06/16 21:22:52 - [NPLogger] - Exception: Unable to cast object of type 'System.String' to type 'Microsoft.SharePoint.Client.FieldLookupValue'.
2024/06/16 21:22:52 - [NPLogger] - Trace:    at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAutoRecord.AddFileDetails(ListItem oItem, String versionsDeletedCount, String versionsDeletedMB)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RemoveFileVersions(SPOTenantItemRecord resultItem)
   at NovaPointLibrary.Solutions.Automation.RemoveFileVersionAuto.RunScriptAsync()
   
   
  manually checking the file, it still has the 500 versions
![VersionHistory](https://github.com/Barbarur/NovaPoint/assets/48899004/09f194fe-5a40-4939-9d84-5fe9b9c5f11e)


Interestingly, (site is out of retention)
I should be able to open the file. IT should then reduce the versions to the minimum set.
Done this in the past as a quick and nasty fix.
It did not reduce the versions.
Tring to delete all versions also, then comes up saying it can't as the site is on hold or retention which it isn't.

So looks to be a MS issue!

**Comment by TheRealStriff** [comment]
OK last test.
Identified a library to test with.

Site is out of retention. No errors but the versions are not deleted.
| SiteUrl | FileTitle | FilePath | FileVersionNo | FileVersionsCount | ItemSizeMb | ItemSizeTotalMB | DeletedVersionsCount | DeletedVersionsMB | Remarks |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| https://o365thiess.sharepoint.com/sites/LakeVermont | Drug and Alcohol Schedule and Summary 2023.xlsx | /sites/LakeVermont/SRHealth/03. Drug and Alcohol/Records/Archive/Drug and Alcohol Schedule and Summary 2023.xlsx | 158 | 137 | 0.04 | 4.46 | 96 | 4.22 | NA |


Have selected to delete (not go into recycle bin), keep 40 versions.
but checking the file, the same amount of versions are present.
I'm able to manually delete files versions (proving retention is not preventing the deletion)

![image](https://github.com/Barbarur/NovaPoint/assets/48899004/f7dd4ea4-17a3-4ffd-9c15-8cf3950516ac)

Will try again later to see

**Comment by TheRealStriff** [comment]
Can confirm version are not being deleted.

Did a Library on Thursday.
Delete all but 30 versions.

Check files after this, no change.

tried again Monday.
Same result, said it was deleting versions, log files sys it is.
Checking the files, the same number of versions as before, no reduction

**Comment by TheRealStriff** [comment]
Ignore anything I said about the versions not being deleted.
I had unknowingly click Report only!

**Comment by Barbarur** [comment]
Implemented new Report Mode form for more clarity from release 0.7.2
