### ISSUE TITLE
Files and Items report

### ISSUE THREAD

**Issue by TheRealStriff** [Barbarur/NovaPoint#33]
Tried this with several sites, with and with the option of adding me as an admin (although I'm already a site collection admin), and No, I am already Admin

It identifies the amount of files, runs, but each time the report fails with: "Maximum retry attempts 10, has be attempted."

Oh also, the GUI has a typo
"Yes, add me Asmin"

![image](https://github.com/user-attachments/assets/0239382b-55ca-4a1a-901c-892534f92747)

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

This might be network issue and the app cannot connect correctly. Or SharePoint has a high workload currently. Try in a different time again.

Check you have the latest version installed. The text typo has been already corrected.

**Comment by TheRealStriff** [comment]
Thanks,
Yes running v0.8.1

All other functions work,
As in can do Versions deletions / remove file versions / preservation hold tasks, set version limits. Seems issue with hust files and items reports so far...
 
Have tried different days times / sites and accounts etc.

**Comment by Barbarur** [comment]
Can you check the log file?

Please share the top part with the parameters you use, and the part of the error message to understand where the error occurs.

The method to get files in this report is exactly the same used to get the files for deleting the versions, so it's strange you get error here and not there.

**Comment by TheRealStriff** [comment]
Sure

Here's the top part (edit out company information)

2024/07/30 00:23:18 - [NPLogger] - Logs: C:\Users\UserXXX\Documents\NovaPoint\ItemReport\240730002318\ItemReport_240730002318_Logs.txt
2024/07/30 00:23:18 - [NPLogger] - Report: C:\Users\UserXXX\Documents\NovaPoint\ItemReport\240730002318\ItemReport_240730002318_Report.csv
2024/07/30 00:23:18 - [NPLogger] - Solution properties
2024/07/30 00:23:18 - [NPLogger] - ========== ========== ==========
2024/07/30 00:23:18 - [NPLogger] - AddAdmin: True
2024/07/30 00:23:18 - [NPLogger] - RemoveAdmin: True
2024/07/30 00:23:18 - [NPLogger] - AllSiteCollections: False
2024/07/30 00:23:18 - [NPLogger] - IncludePersonalSite: False
2024/07/30 00:23:18 - [NPLogger] - IncludeShareSite: False
2024/07/30 00:23:18 - [NPLogger] - OnlyGroupIdDefined: False
2024/07/30 00:23:18 - [NPLogger] - SiteUrl: https://o36XXXX.sharepoint.com/sites/PEAK/
2024/07/30 00:23:18 - [NPLogger] - IncludeSubsites: False
2024/07/30 00:23:18 - [NPLogger] - ListOfSitesPath: 
2024/07/30 00:23:18 - [NPLogger] - AllLists: False
2024/07/30 00:23:18 - [NPLogger] - IncludeLists: False
2024/07/30 00:23:18 - [NPLogger] - IncludeLibraries: False
2024/07/30 00:23:18 - [NPLogger] - IncludeHiddenLists: False
2024/07/30 00:23:18 - [NPLogger] - IncludeSystemLists: False
2024/07/30 00:23:18 - [NPLogger] - ListTitle: PEAK Secure Records
2024/07/30 00:23:18 - [NPLogger] - FolderRelativeUrl: 
2024/07/30 00:23:18 - [NPLogger] - ========== ========== ==========
2024/07/30 00:23:18 - [NPLogger] - Solution has started, please wait to the end
2024/07/30 00:23:23 - [AppInfo] - Finish aquiring new Access Token from AAD
2024/07/30 00:23:23 - [AppInfo] - Access Token expiration time: 30/07/2024 1:53:18 AM +00:00
2024/07/30 00:23:23 - [GraphAPIHandler] - Request Message Uir https://graph.microsoft.com/v1.0/sites/root
2024/07/30 00:23:23 - [GraphAPIHandler] - Successful response
2024/07/30 00:23:23 - [Appinfo] - Hostname: o36XXXX.sharepoint.com

**Comment by Barbarur** [comment]
HI @TheRealStriff ,

Can you share also the part of the log file were we see the error. I would like to see:
- Error Message
- Error Trace
- The 10-20 actions before the error message.

**Comment by TheRealStriff** [comment]
Hello.
Here's two complete logs for two different times.
There's actually no error reported.
(I've edited company information in the logs)
[ItemReport_240728224822_Logs.txt](https://github.com/user-attachments/files/16448548/ItemReport_240728224822_Logs.txt)
[ItemReport_240728231116_Logs.txt](https://github.com/user-attachments/files/16448549/ItemReport_240728231116_Logs.txt)

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

Is the error message the same for both?

For 240728231116 I can see the there is a +30min time when the app is trying to connect. Which match with the error message of 10 attempts.
But for 240728224822 doesn't seems to be any time gap. Is there any file there? I see there is less than 5k items on this.

I've run some test and I can generate the report with libraries below 5k items. I have pending to test large libraries, though I did previously without an issue.

I see the error message is coming from CSOM directly, which usually due network. But it's strange only this report bring an error.

**Comment by TheRealStriff** [comment]
OK, done some more tests, small and large libreires, different sites.
It all seems to now be working,
No difference I've noticed, either network or permissions.
No Throttling, (wasn't getting throttled before)

So not sure what was happening, but thanks for assisting...

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

Thank you for the update.
I've been testing from my side. The only moment I encountered slowness, which could lead into time-out is when I had VPN on. Still it was only slowness and not error.
I've tested it up to 200k recently without issue.
Anyhow, I'm glad it's not working. I'll be closing this for now. If any future error, pelase let me know.
