### ISSUE TITLE
Updating to newer versions

### ISSUE THREAD

**Issue by TheRealStriff** [Barbarur/NovaPoint#35]
I realised on my jump box, I had been installing the newer releases without uninstalling the previous version.

What I found when doing that, in Version 9, going from version 0.8.1 to 0.9.0 (and previously from 0.7.7) is  when running any automation tasks, it would run, but quit out after.

Also, I noticed,  that the menu where it says "Your account need to be Site Collection Admin"
Was still saying "Your account need to be Site Collection Admin
Yes, add me as Asmin / No, I am already Admin"
( instead of Yes / No)

Checking Apps & Features. I could see all three versions still installed.

Easy fix, uninstall all three and install the new version.
Menu is correct, and the app doesn't quit out after running a task.

Cheers

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

Thank you for pointing that out. I'll look into it.

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

From version 0.10.0 the app should prevent parallel installations.
