### ISSUE TITLE
ver 0.9 - delete versions solution doesn't run

### ISSUE THREAD

**Issue by Meisner57** [Barbarur/NovaPoint#36]
tested on a win 11 machine and a fresh install win 10, same issue.
Using latest release (0.9.0), not an upgrade, fresh install, previous versions never installed on the tested machines.

Task starts and authenticates, reports number of total items in doc library, grabs the first bunch of 5000 then immediately errors with error:
TimeSpan overflowed because the duration is too long.

If I roll back to 0.8.1 the process runs correctly.

Could this possibly be due to the "pending time" timer? I noticed when running it on ver 0.8.1 that it starts counting down from 24 hours and then just starts at 24 hours remaining again when it gets to zero. The job I ran took about 48 hours to complete.

I have attached a screenshot of the solution run screen and a copy of the log file. Please note the log is redacted to remove the URL that identifies the sharepoint site.

[ver 0.9 - delete version job dosent run log (redacted).txt](https://github.com/user-attachments/files/16827096/ver.0.9.-.delete.version.job.dosent.run.log.redacted.txt)

![ver 0 9 - delete versions job doesnt run](https://github.com/user-attachments/assets/6dbd0294-c559-45ee-8145-d9febf44d010)

**Comment by TheRealStriff** [comment]
I can also confirm same issue happening to me on version 0.9

**Comment by Barbarur** [comment]
Hi @Meisner57  and @TheRealStriff ,

This should be resolved from version 0.10.0.
