### ISSUE TITLE
ver 0.8.1 - output window doesn't sroll

### ISSUE THREAD

**Issue by Meisner57** [Barbarur/NovaPoint#37]
Simply put the output window doesn't scroll or have a scroll bar when it goes below the bottom of the box. So can't keep track of where its up to.

No other versions have been installed at any time on the machine that this screenshot was generated on. Windows 11.

![ver 0 8 1 - no scroll bar on output window (redacted)](https://github.com/user-attachments/assets/552af82a-bff9-44c3-b7a3-a98c8fc7ecd7)

**Comment by Barbarur** [comment]
Hi @Meisner57 ,

This should be resolved from version 0.9.0, you can test latest v0.10.0
