### ISSUE TITLE
Deleting Versions in Version 11.0

### ISSUE THREAD

**Issue by TheRealStriff** [Barbarur/NovaPoint#39]
Maybe a bug or user error?

Trying to delete versions and retain the latest 30.
Since using this version, it also has the date range.
I have "Keep number of versions" 30
Keep versions created after (UTC) originally left this default. 2010 January 1 00:00

No versions were being deleted. and checking there are certainly lots of files over this amount.
So changed "Keep versions created after (UTC)"  to current date 2024 November 5 0:00
Thinking this may work noting the "The most conservative condition will be honoured per file"

But still no Files were being deleted.

How would you go about with deleting versions ,and only retaining 30, ignoring the dates?

**Comment by TheRealStriff** [comment]
An example this file has 288 versions:

This is from running it with the date 2024 November 5 0:00

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/STRIFF~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/STRIFF~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


FilePath | FileVersionNo | FileVersionsCount | ItemSizeMb | ItemSizeTotalMB | DeletedVersionsCount | DeletedVersionsMB | Remarks
-- | -- | -- | -- | -- | -- | -- | --
/sites/LV/Shared   Documents/MM/Planning/Short Term Planning/Tyre &   Ancillary Documents/Ancillary Status.xlsx | 3185 | 299 | 0.08 | -51.47 | 0 | 0 | No versions to delete



</body>

</html>

**Comment by TheRealStriff** [comment]
and this is an example of leaving the date the default January 1, 2010, 00:00,


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/STRIFF~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/STRIFF~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


https://o365thiess.sharepoint.com/sites/LV| Secure Records | 35240 | LV Rainfall Tracker.xlsx | /sites/LV/Shared   Documents/Technical Services/Environment/Env Reporting/LV Rainfall   Tracker.xlsx | 3637 | 224 | 0.33 | 62.98 | 0 | 0 | No versions to delete
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

For deleting version based on number of ersion to keep ignoring the data, you can set the earliest day available on the drop-down options, as you did.

Did you get any error?
Can you share the log file?

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

Nevermind, please try version 0.11.1, it should be fix.

**Comment by TheRealStriff** [comment]
Thanks.
Testing again.
With the earliest date, and versions to keep to 30.
Will report back

**Comment by TheRealStriff** [comment]
ok, trying version 0.11.1

Looks like it's working now:
To delete based just on versions, have the date set to as early as possible.
![image](https://github.com/user-attachments/assets/59562dcb-1f82-4dea-b0b9-0f976ed2b1fd)
