### ISSUE TITLE
Authentication prompting

### ISSUE THREAD

**Issue by TheRealStriff** [Barbarur/NovaPoint#41]
I found when the authentication timed our in revious versions it would prompted you to re-authenticate and continue on, which is great.

In the Latest version 0.11.1 it does this, but the authentication prompts continuously pop up, instead of jsut the one.

Screen shot shows the numerous prompts from over the week-end
![image](https://github.com/user-attachments/assets/65e964ad-a5a5-49d0-b824-1f605fc67db4)

**Comment by Barbarur** [comment]
Hi @TheRealStriff 

Using any specific Solution or with any solution?
V0.11.0 didn't happen?

**Comment by Barbarur** [comment]
Hi @TheRealStriff ,

How long was the application waiting for authentication?

For V0.11.0 I implemented a timeout of 5min for sign in to prevent the app to stay idle for too long in the middle of processing a solution.

**Comment by TheRealStriff** [comment]
Hi @Barbarur 
Yes sorry was version 0.11.1i.
I only noticed this happening in this version.

Where I work, we have Authentication time out of 7 hours or around that.
So running this tool to clean up versions it can be left over night, and I would sign in again for it to continue.
SO not unusually to be left for 8+ hours.
In this case it was over a weekend where I had no access to check, so a full two days.

I never had an issue with the app being idle for days on end, was actually a great feature, as I could re-authenticate and continue on.

**Comment by Barbarur** [comment]
Please check last release 0.11.2
