### ISSUE TITLE
Site membership report

### ISSUE THREAD

**Issue by IlithanJopie** [Barbarur/NovaPoint#42]
Hello ,

I've been facing an issue when I try the site membership report. I keep getting the message in excel ''The property or field 'IsTeamsConnected' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested."  In the gui I just get '' error processing Site ...... "i checked and all the appropriate rights were issued. 

This leads to most sites not being able to export membership rights. Is this a known issue? I haven't been able to resolve it yet. Thanks in advance for your help

**Comment by Barbarur** [comment]
Please use new release 0.13.1

**Comment by IlithanJopie** [comment]
That fixed it, thanks!
