### ISSUE TITLE
Access token issue

### ISSUE THREAD

**Issue by abelchior77** [Barbarur/NovaPoint#6]
I'm trying to running app but I'm receiving a error that access token cannot be acquired. I configured all settings according setup documentation.

Rgds

**Comment by Barbarur** [comment]
Can you open the .txt log file and paste the full error message here?

It should be at your user's folder "_Documents\NovaPoint\SolutionName_"

**Comment by abelchior77** [comment]
Hello there
 2024/01/17 21:49:02 - [NPLogger] - Logs: C:\Users\duke-admin\Documents\NovaPoint\SiteReport\SiteReport_20240117214902\SiteReport_20240117214902_Logs.txt2024/01/17 21:49:02 - [NPLogger] - Report: C:\Users\duke-admin\Documents\NovaPoint\SiteReport\SiteReport_20240117214902\SiteReport_20240117214902_Report.csv2024/01/17 21:49:02 - [NPLogger] - Solution properties2024/01/17 21:49:02 - [NPLogger] - AdminUPN: 2024/01/17 21:49:02 - [NPLogger] - RemoveAdmin: False2024/01/17 21:49:02 - [NPLogger] - SiteAll: True2024/01/17 21:49:02 - [NPLogger] - IncludePersonalSite: False2024/01/17 21:49:02 - [NPLogger] - IncludeShareSite: True2024/01/17 21:49:02 - [NPLogger] - OnlyGroupIdDefined: False2024/01/17 21:49:02 - [NPLogger] - SiteUrl: 2024/01/17 21:49:02 - [NPLogger] - IncludeSubsites: False2024/01/17 21:49:02 - [NPLogger] - Solution has started, please wait to the end2024/01/17 21:49:02 - [AppInfo.GetSPOAccessToken] - Start getting Access Token for root site https://https://duke-admin.sharepoint.com2024/01/17 21:49:02 - [ProgressUI] - Progress 100%2024/01/17 21:49:02 - [NPLogger.ScriptFinish] - Access Token could not be aquired2024/01/17 21:49:02 - [NPLogger.ScriptFinish] -    at NovaPointLibrary.Commands.Authentication.AppInfo.GetSPOAccessToken(String siteUrl) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\Authentication\AppInfo.cs:line 189   at NovaPointLibrary.Commands.Authentication.AppInfo.GetContext(String siteUrl) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\Authentication\AppInfo.cs:line 143   at NovaPointLibrary.Commands.SharePoint.Site.SPOSiteCollectionCSOM.GetAsync(String siteUrl, Boolean includeShareSite, Boolean includePersonalSite, Boolean onlyGroupIdDefined) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\SharePoint\Site\SPOSiteCollectionCSOM.cs:line 100   at NovaPointLibrary.Solutions.Report.SiteReport.RunScriptAsync() in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Solutions\Report\SiteReport.cs:line 82   at NovaPointLibrary.Solutions.Report.SiteReport.RunAsync() in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Solutions\Report\SiteReport.cs:line 44
At
Atenciosamente,
Alexandre Belchior
***@***.*** 

    On Thursday, January 25, 2024 at 10:26:04 AM GMT-3, Barbarur ***@***.***> wrote:  
 
 


Can you open the .txt log file and paste the full error message here?

It should be at your user's folder "Documents\NovaPoint\SolutionName"

**Comment by Barbarur** [comment]
I think on the settings page you have added ***https://duke***, edit it to keep only the domain name ***duke***.

**Comment by abelchior77** [comment]
Same issue
2024/01/26 15:20:59 - [NPLogger] - Logs: C:\Users\duke-admin\Documents\NovaPoint\SiteReport\SiteReport_20240126152059\SiteReport_20240126152059_Logs.txt2024/01/26 15:20:59 - [NPLogger] - Report: C:\Users\duke-admin\Documents\NovaPoint\SiteReport\SiteReport_20240126152059\SiteReport_20240126152059_Report.csv2024/01/26 15:20:59 - [NPLogger] - Solution properties2024/01/26 15:20:59 - [NPLogger] - AdminUPN: 2024/01/26 15:20:59 - [NPLogger] - RemoveAdmin: False2024/01/26 15:20:59 - [NPLogger] - SiteAll: True2024/01/26 15:20:59 - [NPLogger] - IncludePersonalSite: True2024/01/26 15:20:59 - [NPLogger] - IncludeShareSite: True2024/01/26 15:20:59 - [NPLogger] - OnlyGroupIdDefined: False2024/01/26 15:20:59 - [NPLogger] - SiteUrl: 2024/01/26 15:20:59 - [NPLogger] - IncludeSubsites: False2024/01/26 15:20:59 - [NPLogger] - Solution has started, please wait to the end2024/01/26 15:21:00 - [AppInfo.GetSPOAccessToken] - Start getting Access Token for root site https://duke-admin.sharepoint.com2024/01/26 15:21:01 - [ProgressUI] - Progress 100%2024/01/26 15:21:01 - [NPLogger.ScriptFinish] - Access Token could not be aquired2024/01/26 15:21:01 - [NPLogger.ScriptFinish] -    at NovaPointLibrary.Commands.Authentication.AppInfo.GetSPOAccessToken(String siteUrl) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\Authentication\AppInfo.cs:line 189   at NovaPointLibrary.Commands.Authentication.AppInfo.GetContext(String siteUrl) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\Authentication\AppInfo.cs:line 143   at NovaPointLibrary.Commands.SharePoint.Site.SPOSiteCollectionCSOM.GetAsync(String siteUrl, Boolean includeShareSite, Boolean includePersonalSite, Boolean onlyGroupIdDefined) in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Commands\SharePoint\Site\SPOSiteCollectionCSOM.cs:line 100   at NovaPointLibrary.Solutions.Report.SiteReport.RunScriptAsync() in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Solutions\Report\SiteReport.cs:line 82   at NovaPointLibrary.Solutions.Report.SiteReport.RunAsync() in C:\NovaPoint\NovaPoint-main\src\NovaPointLibrary\Solutions\Report\SiteReport.cs:line 44


Atenciosamente,
Alexandre Belchior
***@***.*** 

    On Friday, January 26, 2024 at 05:30:19 AM GMT-3, Barbarur ***@***.***> wrote:  
 
 


I think on the settings page you have added https://duke, edit it to keep only the domain name duke.

**Comment by abelchior77** [comment]
Barbarur, just a question. Can I run directly from VS or may I compile it and generate a .exe file?
Atenciosamente,
Alexandre Belchior
***@***.*** 

    On Friday, January 26, 2024 at 05:30:19 AM GMT-3, Barbarur ***@***.***> wrote:  
 
 


I think on the settings page you have added https://duke, edit it to keep only the domain name duke.

**Comment by Barbarur** [comment]
You can run it directly on VS, just build and run. No need to compile the .exe or .msi

The only way I'm able to reproduce your issue is when adding ***duke-admin.sharepoint.com*** at the settings page, if adding only ***duke***, I'm not able to reproduce the issue (I'm using my own domain, typing here yours just as reference).

I'm planning to streamline this part to avoid manual typing of the domain and capture the information directly from Graph.

**Comment by abelchior77** [comment]
Hello Barbarur, thank you so much ele for your support here.
Do your device is Azure AD joined or ADDS/hybrid joined? I’m asking this because when I run app in my VM I don’t  receive any authentication request. Just a message about cannot retrieve access token.
Warm regards 

Sent from Yahoo Mail for iPhone


On Friday, January 26, 2024, 11:18 PM, Barbarur ***@***.***> wrote:




You can run it directly on VS, just build and run. No need to compile the .exe or .msi

The only way I'm able to reproduce your issue is when adding duke-admin.sharepoint.com at the settings page, if adding only duke, I'm not able to reproduce the issue (I'm using my own domain, typing here yours just as reference).

I'm planning to streamline this part to avoid manual typing of the domain and capture the information directly from Graph.

**Comment by Barbarur** [comment]
Can you try the latest version? I added some additional logs I hope it help to clarify this kind of issue.


So far I can only see some kind of input error. But we can have it more clear with the new version.


The app doesn't require to run in a domain joined or managed devices. That can only be a requirement from the tenant itself. But I don't think that's your case.

**Comment by Barbarur** [comment]
Domain is now obtained programatically from Graph API without the need to add it on settings. This should avoid any potential typing issue with URLs for obtaining the token.
